kind: pipeline
name: default
#Test 111
steps:
- name: busybox
  image: busybox
  environment:
    PASSWORD:
      from_secret: password
    USERNAME:
      from_secret: username
  commands:
  - echo $PASSWORD
  - echo $USERNAME
  
    
