kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drone-vulume-cache
    volumes:
      - name: cache
        path: /tmp/maven
    settings:
      restore: true
      mount:
        - ./repo
     
         
volumes:
  - name: cache
    host: 
      path: /tmp/cache
      
 
 #触发器
 trigger:
   branch:
     include:
       - master*
   event:
     include:
     - push
