kind: pipeline  
name: default  
#step 1
steps:  
  - name: info  
    image: busybox  
    commands:  
      - echo "hello:world!"  
     
trigger:  
  branch:  
    - master  
  event:  
    - push  
      
